name: linting-action
# Controls when the workflow will run
on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  linter_name:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5.0.0

        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov mypy
          if [ -f requirements.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run type checking using mypy
        run: |
          mypy tios/

      - name: Run tests using pytest
        run: |
          python -m pytest --cov-report term --cov=./tios/ test/
        continue-on-error: true
